services:
  b2-english-prep-suite:
    image: ghcr.io/johnlobo/b2-english-prep-suite:latest
    container_name: b2-english-prep-suite
    restart: unless-stopped
    networks:
      - proxy-network
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FIREBASE_SERVICE_ACCOUNT_KEY_BASE64=${FIREBASE_SERVICE_ACCOUNT_KEY_BASE64}

networks:
  proxy-network:
    external: true
